name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - run: |
          go install github.com/bwplotka/bingo@latest
          PATH=$PATH:~/go/bin bingo get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.35.2
