name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - run: |
          mkdir -p ~/.ssh/
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          go install github.com/bwplotka/bingo@latest
          PATH=$PATH:~/go/bin bingo get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.35.2
